### PR TITLE
Test that install actually works

### LINKED ISSUE #915: "Could not find builtins" error
Hi there.

With the latest dev version of mypy (currently 47b40a77) - since my most recent git pull, I get this error when trying to run mypy:

---------
test.py:1: error: Could not find builtins
---------

Where this is the complete contents of test.py:

---------
#!/usr/bin/env python3.4

print("HELLO WORLD")
---------

And the command-line is:

--------
mypy test.py
--------

(Where I am under a Python virtualenv, where the latest dev version of mypy has been installed).

I ran a git bisect to track down where this issue started, and ended up at this commit where - in my testing - this problem starts manifesting:

------------
commit 2c009ca991bf5d1b42741c0d1a2fbf6bb6077cd4
Author: Ben Longbons <b.r.longbons@gmail.com>
Date:   Tue Jun 30 22:18:20 2015 -0700

    Move script to mypy.main module and just leave stubs

-----------

This is a breaking issue for me - for now I need to do my dev/testing against the commit prior to that, 2e591dcd11, where the problem has not yet manifested.

Please advise?

### PR DESCRIPTION
**Pull request by o11c**
Closes #915 which is critical.

Remaining issues: #917, #732

### CODE REVIEW

**Comment by JukkaL** [comment]
Sorry, I can't review pull requests that change things all over the place without any documentation on what is the purpose of this. Try again by splitting this into atomic changes that address one issue at a time with the smallest reasonable delta -- either a refactoring, a bug fix or a functionality change, and document what each change does. I can't figure out why you are changing things in the tests, for example.

**Comment by o11c** [comment]
Good luck shipping a program that is completely broken then.

I'll just tell everybody to use my fork instead.

**Comment by o11c** [comment]
Also, you're not one to talk at *all* about documentation of internals.

**Comment by JukkaL** [comment]
Please file an issue if something is unclear about the internals. Complaining about it in comments without explaining what is unclear does not improve things.

I can't merge pull requests if I don't understand them, no matter how important the fix is. Are you going to document your PR?
